CREATE TABLE GrupoUniversal (
Id_Grupo INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Nombre_Grupo VARCHAR(30) NOT NULL,
Descripcion VARCHAR(30)) ENGINE MyISAM;


ALTER TABLE imagen 
ADD Id_Grupo INT NOT NULL,
ADD FOREIGN KEY(Id_Grupo)
REFERENCES GrupoUniversal(Id_Grupo)
ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE MyISAM;




CREATE TABLE Usuario(
Id_Usuario VARCHAR(30) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
email VARCHAR( 64 ) NOT NULL ,
username VARCHAR( 16 ) NOT NULL UNIQUE,
password VARCHAR( 32 ) NOT NULL ,
codigo int(7),
activo tinyint(1),
PRIMARY KEY ( Id_Usuario ),
) ENGINE MyISAM;



CREATE TABLE DETALLE_USUARIO_GRUPOUniversal(
Id_Usuario VARCHAR(30),
Id_Grupo INT(7),
BOOL_ADMIN tinyint(1),
FOREIGN KEY(Id_Grupo)
REFERENCES GrupoUniversal(Id_Grupo)
ON UPDATE CASCADE ON DELETE RESTRICT,
FOREIGN KEY(Id_Usuario)
REFERENCES Usuario(Id_Usuario)
ON UPDATE CASCADE ON DELETE RESTRICT,
)


